repos:
  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.3
    hooks:
      - id: bandit
        # skip the assert-used check (B101) which is common in test files
        # and avoid failing commits due to simple tests
        args: ["-r", "src", "tests", "--skip", "B101"]
        pass_filenames: false

  - repo: https://github.com/PyCQA/isort
    rev: 8.0.0
    hooks:
      - id: isort
        args: ["--profile=black", "--filter-files"]

  - repo: https://github.com/psf/black
    rev: 26.1.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy src/app
        language: system
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: uv run pytest -v
        language: system
        pass_filenames: false
        types: [python]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.15.2
    hooks:
      - id: ruff
