FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install --no-cache-dir uv

WORKDIR /workspace

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-cache --no-dev

COPY src ./src

RUN mkdir -p logs

ENV PYTHONPATH=/workspace/src

CMD ["uv", "run", "uvicorn", "app.api.api:fastapi_app", "--host", "0.0.0.0", "--port", "8000"]

EXPOSE 8000
